### PR TITLE
Fix 7947 - Show context menu when right-clicking directory

### LINKED ISSUE #7947: [SourceTree] Context menu doesn't work on directory
STR:

Open any page in debugger
Right click on a directory in the source tree

ER: Context menu should appear
AR: There is no context menu

screenshot 2019-02-13 at 4 01 25 pm

### PR DESCRIPTION
**Pull request by darkwing**
Fixes #7947 

I gave bad flow advice for https://github.com/devtools-html/debugger.html/commit/0ba5f05507c70f41e418bd202ddc29c5376dd581 .    :(

### CODE REVIEW

File: src/components/PrimaryPanes/SourcesTreeItem.js [hunk 1]
```diff
@@ -134,17 +134,18 @@ class SourceTreeItem extends Component<Props, State> {
...
-          label: source.isBlackBoxed
-            ? L10N.getStr("sourceFooter.unblackbox")
-            : L10N.getStr("sourceFooter.blackbox"),
-          accesskey: L10N.getStr("sourceFooter.blackbox.accesskey"),
-          disabled: !shouldBlackbox(source),
-          click: () => this.props.toggleBlackBox(source)
-        };
-
-        menuOptions.push(copySourceUri2, blackBoxMenuItem);
+        if (source) {
```
Comment (jasonLaster) [inline src/components/PrimaryPanes/SourcesTreeItem.js]: maybe we should replace the checks above `if (!Array.isArray(contents)) {` which seems like it is doing the same thing

**Comment by darkwing** [comment]
It would show the set/remove directory root
